# ansible-vault encrypt_string --vault-password-file ~/.password 'Test123456!2' --name 'user_service_db_passwd'
# ansible-playbook user-service.yml --vault-password-file ~/.password


- hosts: 127.0.0.1
  connection: local
  vars_files:
  - /home/ubuntu/secrets/group_vars/secrets_management/vars.yml

  tasks:
  - name: Basic Templating
    template:
      src:  /home/ubuntu/secrets/templates/app.properties.j2
      dest: /tmp/user1/app.properties
      mode: '0644'