# ansible-playbook user-service.yml --vault-password-file ~/.password
- hosts: 127.0.0.1
  connection: local
  vars_files:
  - /home/ubuntu/sm/ansible/roles/secrets_management/group_vars/vars.yml

  tasks:
  - name: Basic Templating
    template:
      src:  /home/ubuntu/sm/ansible/roles/secrets_management/templates/app.properties.j2
      dest: /tmp/secrets_management/app.properties
      mode: '0644'